- component/chat.js
- component/generate.js
- component/starList.js
closed #11
starList.js, generate.js, chat.js 임시 업로드
> [feat #11] starList.js, generate.js, chat.js 임시 업로드

- component/starList.js
> [fix #13] starList 긴급수정

- App.js
- component/join.js
- component/login.js
- package-lock.json
- package.json
closed #17
로그인 및 회원가입 API연결 함. 회원가입 및 로그인까지 되는거 확인
> [feat #17] 로그인 및 회원가입 API연결

- component/starList.js
> [feat #19] generate 팝업으로 전환

- App.js
- component/join.js
- component/kakao_login.js
- component/login.js
- component/starList.js
- package-lock.json
- package.json
> [feat/24] 카카오 API.js업데이트

- .env
- .gitignore
- app.json
- component/kakao_login.js
> [feat #24] 카카오 API.js업데이트 추가 수정

- .env
> [fix #27] .env 삭제

- package.json
> [fix #34] package.json 수정

- component/join.js
- component/kakao_login.js
closed #37 
카카오 로그인 코드 변경 및 회원가입 에러 수정
> [feat #37] 카카오 로그인 코드 변경 및 회원가입 에러 수정

- App.js
- admin/components/adminList.js
- admin/components/userDetail.js
- admin/components/userList.js
- admin/navigation/admin.js
- component/generate.js
- component/join.js
- component/kakao_login.js
- component/login.js
- component/starList.js
- package-lock.json
- package.json
closed #33 
admin 프론트 옮기고 페이지네이션 기능 구현과 백엔드 연결했습니다.
아직 admin은 admin계정으로 로그인하면 admin페이지로 접속되는 부분은 구현하지 않았기 떄문에
App.js에서 Stack.Screen에 Admin과 UserDetail 빼고 
다른 Stack.Screen들을 모두 주석처리 해주시고 들어가야 관리자 페이지로 접속할 수 있습니다.
> [feat #33] admin 백엔드 연결

- App.js
- component/join.js
> [feat #43] 회원가입 이메일 중복체크

- admin/components/userDetail.js
- admin/components/userList.js
- component/join.js
- component/kakao_login.js
- component/login.js
- component/mypage.js
- component/starList.js
> [fix #46] API_URL 추가 수정

- auth/join.js
closed #53
Admin components name 수정 / AccessToken 추가
> [fix #53] Admin Components명 수정 / AccessToken 추가

- App.js
- component/member.js
- component/mypage.js
- component/setting.js
- component/starList.js
- package-lock.json
- package.json
closed #51 
마이페이지 회원정보 불러오기까지(DB업데이트전)
> [feat #51] 마이페이지 회원정보 불러오기까지(DB업데이트전)

- auth/kakao_login.js
- component/member.js
- component/pwupdate.js
- component/setting.js
> [feat #58] 카카오 로그인 마이페이지 변경

- App.js
- component/chat.js
- component/starList.js
- hooks/useSocket.js
- package-lock.json
- package.json
> [feat #52] AI 모델 및 백엔드 연결 완료

- component/chat.js
closed #62 
채팅방 아바타 (프로필 이미지) 가져오기
> [feat #62] 채팅방 아바타 (프로필 이미지) 가져오기

- component/chat.js
- component/generate.js
closed #66
generate 성별 선택
chat IMG 오류 해결
> [feat #66] generate 성별 선택

- App.js
- auth/join.js
- auth/login.js
- component/main.js
- component/member.js
- component/mypage.js
- component/pwupdate.js
- component/setting.js
- component/starList.js
> [feat #64] 마이페이지 및 로그인 변경

- component/generate.js
> [fix #68] gender 추가오류 수정

- component/delete.js
> [feat #70] 마이페이지 회원탈퇴 추가

- component/starList.js
> [feat #74] 스타리스트 채팅 최신화

- component/chat.js
- component/starList.js
- package-lock.json
- package.json
> [fix #78] 채팅 아바타 랜더링 오류 해결

- component/starList.js
closed #83
starList image 오류 수정
> [fix #83] starList image 오류 수정

- auth/login.js
- component/main.js
- component/setting.js
- component/starList.js
> [feat #88] 로그아웃 기능 추가

- component/starList.js
closed #82> 
star Image, name 수정, star 삭제기능추가
> [feat #81] star Image, name 수정, star 삭제기능추가

- component/generate.js
- component/starList.js
> [fix #92] generate 종료시 모달 닫기

- auth/join.js
- auth/login.js
- component/delete.js
- component/generate.js
- component/loading.js
- component/member.js
- component/mypage.js
- component/starList.js
- package-lock.json
> [fix #94] 프론트 UI수정

- component/generate.js
- component/starList.js
> [fix #98] Alert 오류 수정

- auth/join.js
- auth/login.js
- component/delete.js
- component/generate.js
- component/mypage.js
- component/pwupdate.js
> [refactor #102] 프론트 UI수정
